import "./addDebateTime";
import "./addProposal";
import "./deposit";
import "./finishProposal";
import "./setDebateDuration";
import "./setPropAdmin";
import "./unsetPropAdmin";
import "./vote";
import "./withdraw";